# Generated by Codex for initial project bootstrap.
import stylist.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Occasion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Occasion",
                "verbose_name_plural": "Occasions",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="StyleTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="StylingRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("additional_info", models.TextField(blank=True)),
                ("image_original", models.ImageField(blank=True, null=True, upload_to=stylist.models.original_upload_path)),
                ("image_optimized", models.ImageField(blank=True, null=True, upload_to=stylist.models.optimized_upload_path)),
                (
                    "status",
                    models.CharField(
                        choices=[("QUEUED", "Queued"), ("RUNNING", "Running"), ("DONE", "Done"), ("FAILED", "Failed")],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("ai_model", models.CharField(blank=True, max_length=128)),
                ("ai_latency_ms", models.IntegerField(blank=True, null=True)),
                ("ai_usage", models.JSONField(blank=True, null=True)),
                ("files_deleted", models.BooleanField(default=False)),
                (
                    "occasion",
                    models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="styling_requests", to="stylist.occasion"),
                ),
                (
                    "season",
                    models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="styling_requests", to="stylist.season"),
                ),
                (
                    "style",
                    models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="styling_requests", to="stylist.styletag"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="stylingrequest",
            index=models.Index(fields=["status"], name="stylist_sty_status_44663f_idx"),
        ),
        migrations.AddIndex(
            model_name="stylingrequest",
            index=models.Index(fields=["created_at"], name="stylist_sty_created_ec57d8_idx"),
        ),
    ]
