# Generated by Codex for generated outfit image support.
import stylist.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stylist", "0002_seed_reference_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylingrequest",
            name="generated_image",
            field=models.ImageField(blank=True, null=True, upload_to=stylist.models.generated_upload_path),
        ),
        migrations.AddField(
            model_name="stylingrequest",
            name="image_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stylingrequest",
            name="image_latency_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stylingrequest",
            name="image_model",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
