# Generated by Django 5.1.6 to align auto-generated index names.
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stylist", "0003_stylingrequest_generated_image"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stylingrequest",
            old_name="stylist_sty_status_44663f_idx",
            new_name="stylist_sty_status_5eb0e9_idx",
        ),
        migrations.RenameIndex(
            model_name="stylingrequest",
            old_name="stylist_sty_created_ec57d8_idx",
            new_name="stylist_sty_created_ce34c7_idx",
        ),
    ]
